
version: '3'
services:
  elasticsearch:
    image: elasticsearch:8.17.1
    ports:
      - 9200:9200
    environment:
      discovery.type: 'single-node'
      xpack.security.enabled: 'true'
      ELASTIC_PASSWORD: 'hieunt04lm'
      ES_JAVA_OPTS: '-Xmx2g -Xms2g'
  kibana:
    image: kibana:8.17.1
    volumes:
      - ./kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - 5601:5601